export const RANDOM_WORDS = [
    "apple", "banana", "cherry", "dog", "elephant", "fox", "grape", "house", "island", "jungle",
    "kite", "lemon", "mountain", "notebook", "orange", "piano", "queen", "river", "sun", "tiger",
    "umbrella", "violin", "whale", "xylophone", "yacht", "zebra", "happy", "sad", "angry", "brave",
    "bright", "calm", "careful", "clever", "crazy", "dangerous", "eager", "famous", "friendly", "funny",
    "gentle", "grumpy", "helpful", "honest", "hungry", "important", "kind", "lazy", "lucky", "modern",
    "nervous", "nice", "noisy", "polite", "proud", "quiet", "scared", "shy", "silly", "sleepy", "smart",
    "strong", "stupid", "successful", "thoughtful", "tired", "useful", "weak", "worried", "young", "old",
    "blue", "red", "green", "yellow", "purple", "black", "white", "brown", "pink", "gray",
    "big", "small", "short", "tall", "fast", "slow", "hot", "cold", "soft", "hard",
    "good", "bad", "right", "wrong", "easy", "difficult", "light", "dark", "early", "late", "heavy", "loud",
    "kitten", "puppy", "rabbit", "turtle", "hamster", "parrot", "goldfish", "squirrel", "chinchilla",
    "hedgehog", "ferret", "gerbil", "mouse", "rat", "chameleon", "gecko", "iguana", "bearded dragon", "snake",
    "frog", "toad", "newt", "salamander", "axolotl", "tarantula", "scorpion", "millipede", "centipede", "crab",
    "cow", "pig", "sheep", "goat", "horse", "donkey", "llama", "alpaca", "camel", "rhinoceros",
    "cello", "flute", "clarinet", "trumpet", "trombone", "saxophone", "drum", "guitar",
    "bass", "harp", "accordion", "banjo", "mandolin", "ukulele", "harmonica", "bagpipes", "oboe", "bassoon",
    "shirt", "pants", "dress", "skirt", "blouse", "sweater", "jacket", "coat", "hat", "scarf", "gloves",
    "boots", "shoes", "sneakers", "sandals", "heels", "flats", "slippers", "flip-flops", "pajamas", "robe",
    "desk", "chair", "table", "couch", "sofa", "bed", "dresser", "nightstand", "bookshelf", "lamp",
    "rug", "curtains", "blinds", "mirror", "clock", "calendar", "picture", "painting", "sculpture", "vase",
    "plate", "bowl", "cup", "mug", "glass", "fork", "knife", "spoon", "chopsticks", "napkin",
    "oven", "stove", "microwave", "refrigerator", "freezer", "dishwasher", "sink", "toaster", "blender",
    "jump", "run", "walk", "skip", "hop", "crawl", "swim", "dance", "sing", "play", "read", "write", "draw",
    "paint", "cook", "bake", "clean", "organize", "exercise", "stretch", "meditate", "relax", "sleep", "dream",
    "work", "study", "learn", "teach", "help", "volunteer", "donate", "recycle", "upcycle", "repair", "create",
    "internet", "computer", "laptop", "tablet", "phone", "smartphone", "smartwatch", "television", "radio", "headphones",
    "speaker", "microphone", "camera", "printer", "scanner", "projector", "keyboard", "mouse", "monitor", "modem",
    "code", "program", "design", "develop", "test", "debug", "deploy", "maintain", "update", "upgrade", "backup",
    "restore", "encrypt", "decrypt", "compress", "decompress", "format", "partition", "network", "connect", "communicate",
    "collaborate", "research", "analyze", "evaluate", "interpret", "conclude", "present", "publish", "share", "comment",
    "like", "dislike", "subscribe", "follow", "block", "report", "delete", "ban", "hack", "crack", "spam",
    "scam", "phish", "virus", "malware", "spyware", "adware", "trojan", "worm", "plant", "harvest", "water",
    "weed", "prune", "fertilize", "pollinate", "propagate", "graft", "clone", "grow", "bloom", "flower", "fruit",
    "vegetable", "herb", "spice", "nut", "seed", "root", "stem", "leaf", "branch", "trunk", "bark", "ambrosia", 
    "nectar", "game", "win", "lose", "draw", "tie", "score", "point", "level", "stage", "round", "match",
    "tournament", "champion", "challenger", "opponent", "team", "squad", "coach", "referee", "player", "fan", "supporter",
    "cheer", "boo", "clap", "whistle", "chant", "celebrate", "party", "host", "guest", "invite",
    "tennis", "badminton", "ping-pong", "volleyball", "basketball", "football", "soccer", "baseball", "softball", "hockey",
    "lacrosse", "rugby", "cricket", "golf", "polo", "bowling", "billiards", "pool", "snooker", "darts", "archery",
    "fencing", "wrestling", "boxing", "karate", "taekwondo", "judo", "jiu-jitsu", "aikido", "kung fu", "muay thai",
    "grandma", "grandpa", "mom", "dad", "sister", "brother", "aunt", "uncle", "cousin", "niece", "nephew", "child",
    "children", "kid", "teen", "adult", "parent", "family", "relative", "ancestor", "descendant", "generation", "lineage",
    "friend", "bestie", "buddy", "pal", "mate", "comrade", "chum", "partner", "ally", "confidant", "mentor", "teacher",
    "student", "classmate", "roommate", "neighbor", "colleague", "coworker", "boss", "employee", "client", "customer", "patient",
    "doctor", "nurse", "therapist", "counselor", "psychologist", "psychiatrist", "social worker", "case manager", "advocate", "activist", "organizer",
    "leader", "follower", "member", "volunteer", "donor", "sponsor", "supporter", "ally", "partner", "community", "society", "organization",
    "group", "team", "club", "association", "union", "coalition", "alliance", "network", "system", "structure", "process", "procedure",
    "protocol", "policy", "practice", "program", "plan", "project", "goal", "desktop", "router", "switch", "hub", "server",
    "cloud", "database", "file", "folder", "directory", "drive", "disk", "memory", "storage", "backup", "restore",
    "painting", "drawing", "sketch", "doodle", "illustration", "portrait", "landscape", "still life", "abstract", "realistic",
    "toy", "puzzle", "block", "ball", "doll", "vehicle", "train", "plane", "car",
    "truck", "boat", "ship", "rocket", "spaceship", "robot", "monster", "animal", "dinosaur", "dragon", "unicorn",
    "mermaid", "fairy", "elf", "wizard", "witch", "sorcerer", "mage", "cleric", "paladin", "ranger", "rogue",
    "warrior", "barbarian", "monk", "druid", "bard", "fighter", "frame", "canvas", "paper", "board", "wood", "metal", "plastic",
    "glass", "ceramic", "fabric", "thread", "needle", "scissors", "knife", "brush", "pen", "pencil", "crayon", "marker", "chalk", 
    "charcoal", "pastel", "watercolor", "acrylic", "oil", "ink", "digital", "analog", "traditional", "contemporary", "modern", "abstract", "realistic"
];
