export const ZEN_WORDS = [
    "peace", "calm", "serene", "tranquil", "harmony", "stillness", "balance", "flow", "breathe", "meditate",
    "relax", "mindful", "present", "quiet", "nature", "gentle", "soft", "cloud", "breeze", "water",
    "forest", "ocean", "river", "mountain", "valley", "zen", "lotus", "bamboo", "moon", "sunset",
    "dawn", "dusk", "simplicity", "ease", "soothe", "warmth", "kindness", "compassion", "accept", "clarity",
    "wisdom", "patience", "gratitude", "forgive", "awareness", "silence", "content", "joy", "happiness", "smile",
    "gentleness", "presence", "whisper", "flowing", "drifting", "floating", "illumination", "light", "energy", "softness",
    "deep", "vast", "open", "fresh", "pure", "trust", "freedom", "connection", "wholeness", "being",
    "now", "simplicity", "essence", "surrender", "renew", "rest", "pause", "zenith", "glow", "starlight",
    "rain", "dewdrop", "butterfly", "blossom", "wave", "echo", "horizon", "meditation", "sacred", "unity",
    "serenity", "murmur", "whispering", "tranquility", "lightness", "breath", "cozy", "comfort", "kensho", 
    "satori", "ukiyo", "kaizen", "illumoria", "veilon", "tea", "chill", "blanket", "cocoon", "snuggle",
    "quietude", "fireside", "hygge", "candlelight", "peacefulness", "tender", "contentment", "embrace", "unwind",
    "chamomile", "amber", "mellow", "wholesome", "cuddle", "sweet", "lullaby", "crackling", "softness",
    "slumber", "dream", "melancholy", "serene", "plush", "quilt", "breeze", "shanti", "shelter", "balmy",
    "lumiere", "douceur", "serenite", "paix", "zenith", "sakura", "harmony", "noir", "detente", "repos",
    "relaxer", "lune", "soothe", "bambou", "ecume", "mousse", "belle", "tranquillo", "calma", "reposo", 
    "mizu", "aqua", "doux", "neige", "gaite", "luce", "viento", "relajacion", "sabiduria", "esencia", "fleur",
    "solace", "monde", "calme", "sillage", "generosite", "cosy", "bambou", "miracle", "bienetre", "sereno", "paz",
    "frisson", "serenite", "legerete", "plenitude", "liberte", "calma", "chaleur", "souk", "piacevole", "solace"
];
